expose:
  type: clusterIP
  tls:
    enabled: false

externalURL: http://harbor-harbor-core.harbor.svc.cluster.local

harborAdminPassword: "Harbor12345"

persistence:
  persistentVolumeClaim:
    registry:
      size: 5Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi

# add these to stop endless rollouts:
secretKey: "harbor-cookie-secret-16ch+"
core:
  secret: "core-secret-16ch++++"
jobservice:
  secret: "jobsvc-secret-16ch++"
registry:
  secret: "registry-secret-16ch"
portal:
  secret: "portal-secret-16ch++"


chartmuseum:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: false