apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-runner-set-gha-rs-manager
  namespace: github-actions-runner-set
  labels:
    app.kubernetes.io/name: github-actions-runner-set
    app.kubernetes.io/instance: github-actions-runner-set
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: github-actions-runner-set
    actions.github.com/scale-set-namespace: github-actions-runner-set
    app.kubernetes.io/component: manager-role-binding
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions-runner-set-gha-rs-manager
subjects:
  - kind: ServiceAccount
    name:
      github-action-controller-gha-rs-controller
    namespace:
      github-action-controller