apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: main-agent
  namespace: observability
spec:
  serviceScrapeSelector: {}
  serviceScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  nodeScrapeSelector: {}
  extraArgs:
    promscrape.dropOriginalLabels: "false"
  remoteWrite:
    - url: "http://victoria-metrics-server.observability.svc:8428/api/v1/write"