apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet-cadvisor
  namespace: observability
spec:
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"  # VMAgent повинен мати SA з правами
  path: /metrics/cadvisor
  interval: 30s
  honorLabels: true
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - sourceLabels: [__address__]
      targetLabel: instance
      replacement: $1
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet-metrics
  namespace: observability
spec:
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  path: /metrics
  interval: 30s
  honorLabels: true
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)