grafana.ini:
  auth:
    disable_login_form: true
  auth.anonymous:
    enabled: true
    org_role: Admin

deploymentStrategy:
  type: Recreate

adminPassword: admin

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
initChownData:
  enabled: false

persistence:
  enabled: true
  storageClassName: local-nvme
  size: 5Gi

sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL

dashboards:
  default:
    kafka-dashboard:
      gnetId: 24626
      revision: latest
      datasource: VictoriaMetrics
#    kubernetes-dashboard:
#      gnetId: 15661
#      revision: 2
#      datasource: VictoriaMetrics

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        type: file
        options:
          path: /var/lib/grafana/dashboards/default