apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: strimzi-kafka-metrics
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
      strimzi.io/cluster: my-cluster
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s