apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /system/postgresql/DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: /system/postgresql/DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: /system/postgresql/DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: /system/postgresql/DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /system/postgresql/DB_PASSWORD
    - secretKey: ROOT_PASSWORD
      remoteRef:
        key: /system/postgresql/ROOT_PASSWORD
