apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
    targetRevision: homelab
    path: 03-gitops/applications/03-observability
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}