apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: core
  sources:
    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      path: 03-gitops/components/00-core/cloudflared

    - repoURL: https://community-charts.github.io/helm-charts
      chart: cloudflared
      targetRevision: 2.2.6
      helm:
        valueFiles:
          - $values/03-gitops/components/00-core/cloudflared/values.yaml

    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true