apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: core
  source:
    repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
    targetRevision: homelab
    path: 03-gitops/components/00-core/gateway-system
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true