apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      path: 03-gitops/apps/system/observability/prometheus-node-exporter/app

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.51.1
      helm:
        valueFiles:
          - $values/03-gitops/apps/system/observability/prometheus-node-exporter/app/values.yaml

    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true