githubConfigSecret: controller-manager
githubConfigUrl: https://github.com/planeops/ci-runners


controllerServiceAccount:
  namespace: github-action-controller
  name: github-action-controller-gha-rs-controller

template:
  spec:
    labels:
      - self-hosted
      - linux
      - planeops