provider: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: CF_API_TOKEN

domainFilters:
  - "serhii.link"

policy: sync
txtOwnerId: "external-dns"

sources:
  - ingress

logLevel: debug

serviceAccount:
  create: true
  name: external-dns