apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-runner-set-gha-rs-no-permission
  namespace: github-actions-runner-set
  labels:
    app.kubernetes.io/name: github-actions-runner-set
    app.kubernetes.io/instance: github-actions-runner-set
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: github-actions-runner-set
    actions.github.com/scale-set-namespace: github-actions-runner-set
  annotations: