tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

config:
  pipeline:
    inputs:
      - name: tail
        alias: k8s-logs
        path: /var/log/containers/*_kube-system_*.log
        exclude_path: /var/log/containers/*fluent-bit*.log,/var/log/containers/*fluentbit*.log
        tag: kube.*
        read_from_head: true
        multiline.parser: cri

    filters:
      - name: kubernetes
        match: kube.*
        merge_log: false
        keep_log: true
        labels: false
        annotations: false

      - name: nest
        match: kube.*
        operation: lift
        nested_under: kubernetes
        add_prefix: k8s_

      - name: record_modifier
        match: kube.*
        allowlist_key:
          - log
          - log_type
          - k8s_namespace_name
          - k8s_pod_name
          - k8s_container_name
          - k8s_host

      - name: modify
        match: kube.*
        add: log_type infrastructure


    outputs:
      - name: opentelemetry
        match: kube.*
        host: otel-gateway-collector.observability.svc
        port: 4318
        logs_uri: /v1/logs
        tls: off
        logs_body_key: log
        logs_body_key_attributes: true