apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-test-apps-producer
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: sensor-data
        operations: [ Write, Create, Describe ]
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-test-apps-consumer
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: sensor-data
        operations: [ Read, Describe ]
      - resource:
          type: group
          name: my-kafka-consumer
        operations: [ Read ]
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: sensor-data
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 1073741824
    retention.ms: 86400000
    segment.bytes: 1073741824