apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: ghcr.io/serhiimyronets/producer:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: TOPIC
              value: sensor-data
            - name: PRODUCE_INTERVAL
              value: "1"
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/kafka/ca
              readOnly: true
            - name: user-tls
              mountPath: /etc/kafka/user
              readOnly: true
      volumes:
        - name: cluster-ca
          secret:
            secretName: my-cluster-cluster-ca-cert
        - name: user-tls
          secret:
            secretName: kafka-test-apps-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: ghcr.io/serhiimyronets/consumer:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: postgresql-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: TOPIC
              value: sensor-data
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/kafka/ca
              readOnly: true
            - name: user-tls
              mountPath: /etc/kafka/user
              readOnly: true
      volumes:
        - name: cluster-ca
          secret:
            secretName: my-cluster-cluster-ca-cert
        - name: user-tls
          secret:
            secretName: kafka-test-apps-consumer
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-dashboard
  name: kafka-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-dashboard
  template:
    metadata:
      labels:
        app: kafka-dashboard
    spec:
      containers:
        - name: kafka-dashboard
          image: ghcr.io/serhiimyronets/dashboard:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: API_BASE_URL
              value: http://kafka-consumer-service:8080
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-dashboard-service
spec:
  selector:
    app: kafka-dashboard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-dashboard-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main-gateway
      namespace: gateway-system
  hostnames:
    - kafka-dashboard.serhii.link
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: kafka-dashboard-service
          port: 3000
          weight: 1