apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - namespace.yaml
  - httproute.yaml
helmCharts:
  - name: onlineboutique
    repo: oci://us-docker.pkg.dev/online-boutique-ci/charts
    version: 0.10.7
    releaseName: online-boutique
    namespace: online-boutique
    valuesFile: values.yaml
