apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bind-tsig
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloud
  target:
    name: bind-tsig
  data:
    - secretKey: TSIG_SECRET
      remoteRef: {key: /system/bind/TSIG_SECRET}
