apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-demo
  namespace: otel-demo
spec:
  image: otel/opentelemetry-collector-contrib:latest
  mode: deployment
  replicas: 1
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
          - key: service.instance.id
            from_attribute: k8s.pod.uid
            action: insert
      batch:
        send_batch_size: 1024
        timeout: 5s

    exporters:
      # Metrics → VictoriaMetrics
      prometheusremotewrite/vm:
        endpoint: http://victoria-metrics-server.observability.svc.cluster.local:8428/api/v1/write
        tls:
          insecure: true
        resource_to_telemetry_conversion:
          enabled: true

      # Logs → Loki
      otlp_http/loki:
        endpoint: http://loki.observability.svc:3100/otlp
        tls:
          insecure: true

      # Traces → Tempo
      otlp_grpc/tempo:
        endpoint: tempo.observability.svc.cluster.local:4317
        tls:
          insecure: true

      debug:
        verbosity: basic

    connectors:
      spanmetrics: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp_grpc/tempo, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [memory_limiter, resource, batch]
          exporters: [prometheusremotewrite/vm]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp_http/loki]
      telemetry:
        metrics:
          level: basic