apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      path: 03-gitops/apps/services/otel-demo/app

    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-demo
      targetRevision: 0.40.7
      helm:
        valueFiles:
          - $values/03-gitops/apps/services/otel-demo/app/values.yaml

    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true