apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /datadog/api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: site
      remoteRef:
        key: /datadog/site
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None