apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloud
  target:
    name: tunnel-credentials
  data:
    - secretKey: credentials.json
      remoteRef: {key: /system/cloudflare/TUNNEL_CREDENTIALS}
