apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
#  labels:
#    helm.sh/chart: buildkit-service-0.10.0
#    app.kubernetes.io/name: buildkit-service
#    app.kubernetes.io/instance: buildkit
#    app.kubernetes.io/version: "v0.21.0"
#    app.kubernetes.io/managed-by: Helm
  namespace: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkit-service
      app.kubernetes.io/instance: buildkit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkit-service
        app.kubernetes.io/instance: buildkit
    spec:
      containers:
        - name: buildkit-service
          image: "moby/buildkit:v0.21.0"
          imagePullPolicy: IfNotPresent
          args:
            - --addr
            - unix:///run//buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --config
            - /etc/buildkit/buildkitd.toml
          envFrom:
            - secretRef:
                name: buildkit-minio-secret
          volumeMounts:
            - name: buildkitd-config
              mountPath: /etc/buildkit
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: buildkitd-config
          configMap:
            name: buildkitd-config