apiVersion: v1
kind: Service
metadata:
  name: buildkit-service
#  labels:
#    helm.sh/chart: buildkit-service-0.10.0
#    app.kubernetes.io/name: buildkit-service
#    app.kubernetes.io/instance: buildkit
#    app.kubernetes.io/version: "v0.21.0"
#    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: buildkit-service
    app.kubernetes.io/instance: buildkit
