apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      path: 03-gitops/components/01-platform/strimzi

    - repoURL: https://strimzi.io/charts
      chart: strimzi-kafka-operator
      targetRevision: 0.50.1
      helm:
        valueFiles:
          - $values/03-gitops/components/01-platform/strimzi/values.yaml

    - repoURL: https://github.com/serhii-myronets/terraform-talos-gitops-cluster.git
      targetRevision: homelab
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true