apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buildkit-minio-secret
  namespace: buildkit
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: minio-access-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /minio/minio-accessKey
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /minio/minio-secretKey
    - secretKey: AWS_REGION
      remoteRef:
        key: /minio/minio-region
    - secretKey: AWS_BUCKET
      remoteRef:
        key: /minio/minio-bucket
