config:
  redirectURL: "https://oauth.serhii.link/oauth2/callback"
  upstreams:
    - "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80/"
  existingSecret: oauth2-proxy-token
  configFile: |
    provider = "github"
    scope = "user:email read:org read:user"
    email_domains = [ "*" ]
    cookie_domains = [ ".serhii.link" ]
    whitelist_domains = [ ".serhii.link" ]
    cookie_secure = true
    github_users = [ "SerhiiMyronets" ]


#ingress:
#  enabled: true
#  className: nginx
#  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#  hosts:
#    - oauth.serhii.link

ingress:
  enabled: false

gatewayApi:
  enabled: true
#  gatewayRef:
#    name: public-gw
#    namespace: networking
#  hostnames:
#    - oauth.serhii.link
#  rules:
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /