crds:
  enabled: false


kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: "10GB"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    # English comment: Talos-specific fix for node-exporter
    hostNetwork: true

grafana:
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_role: Admin

  deploymentStrategy:
    type: Recreate

  adminPassword: admin

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  initChownData:
    enabled: false
  
  persistence:
    enabled: true
    storageClassName: local-nvme
    size: 5Gi
