apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-access-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cloud
    kind: ClusterSecretStore
  target:
    name: minio-access-secret
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: /system/minio/ACCESS_KEY_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secretKey
      remoteRef:
        key: /system/minio/SECRET_ACCESS_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None