apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  namespace: observability
spec:
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: accessKey
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: secretKey

  mode: deployment
  replicas: 1
  image: otel/opentelemetry-collector-contrib:latest

  config:
    receivers:

      k8s_events:
        auth_type: serviceAccount
        namespaces: []

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:

      resource/cluster_logs:
        attributes:
          - key: service.name
            value: logs
            action: upsert
          - key: service.namespace
            value: cluster
            action: upsert

      resource/cluster_events:
        attributes:
          - key: service.name
            value: events
            action: upsert
          - key: service.namespace
            value: cluster
            action: upsert

      resource/service_logs:
        attributes:
          - key: service.name
            value: logs
            action: upsert
          - key: service.namespace
            value: services
            action: upsert

      transform/events_severity:
        log_statements:
          - context: log
            statements:
              # 1. Set default severity for all events first
              - set(log.severity_number, 9)
              - set(log.severity_text, "INFO")

              # 2. Upgrade severity for specific error conditions
              - set(log.severity_number, 17) where attributes["k8s.event.reason"] == "OOMKilling"
              - set(log.severity_text, "ERROR") where attributes["k8s.event.reason"] == "OOMKilling"

              - set(log.severity_number, 17) where attributes["k8s.event.reason"] == "FailedScheduling"
              - set(log.severity_text, "ERROR") where attributes["k8s.event.reason"] == "FailedScheduling"

              - set(log.severity_number, 17) where attributes["k8s.event.reason"] == "NodeNotReady"
              - set(log.severity_text, "ERROR") where attributes["k8s.event.reason"] == "NodeNotReady"

              # 3. Handle Warnings
              - set(log.severity_number, 13) where attributes["k8s.event.reason"] == "Error"
              - set(log.severity_text, "WARN") where attributes["k8s.event.reason"] == "Error"

              - set(log.severity_number, 13) where attributes["k8s.event.reason"] == "BackOff"
              - set(log.severity_text, "WARN") where attributes["k8s.event.reason"] == "BackOff"

      filter/events_drop_routine:
        error_mode: ignore
        logs:
          log_record:
            # Drop routine lifecycle events
            - 'attributes["k8s.event.reason"] == "Valid"'
            - 'attributes["k8s.event.reason"] == "Scheduled"'
            - 'attributes["k8s.event.reason"] == "Pulled"'
            - 'attributes["k8s.event.reason"] == "Created" and attributes["k8s.object.kind"] == "Pod"'
            - 'attributes["k8s.event.reason"] == "Started" and attributes["k8s.object.kind"] == "Pod"'

      batch:
        timeout: 60s
        send_batch_size: 10000

    exporters:
      prometheusremotewrite:
        endpoint: "http://victoria-metrics-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write"
      debug: {}

      otlp_http/loki:
        endpoint: "http://loki.observability.svc:3100/otlp"

      awss3:
        s3uploader:
          endpoint: "http://minio.minio.svc:9000"
          region: us-east-1
          s3_bucket: logs-cold-storage
          s3_force_path_style: true
          s3_partition_format: '%Y/%m/%d/%H'
          compression: gzip
        resource_attrs_to_s3:
          s3_prefix: service.name
#        timeout: 60s

    service:
      pipelines:
#        metrics:
#          receivers: [otlp]
#          processors: [batch]
#          exporters: [prometheusremotewrite, debug]

        logs/cluster_events:
          receivers: [k8s_events]
          processors: [filter/events_drop_routine, transform/events_severity, resource/cluster_events, batch]
          exporters: [otlp_http/loki, awss3]

        logs/cluster_logs:
          receivers: [otlp]
          processors: [resource/cluster_logs, batch]
          exporters: [otlp_http/loki, awss3]